name: Build, Release and Deploy Fat JAR

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build-release-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Fat JAR
        run: ./gradlew clean build shadowJar -x integrationTest

      - name: Extract Tag Name
        id: extract_tag
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload JAR to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/libs/trendaizer-${{ steps.extract_tag.outputs.tag_name }}-all.jar
          asset_name: trendaizer-${{ steps.extract_tag.outputs.tag_name }}-all.jar
          asset_content_type: application/java-archive

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1071463491007/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "github-actions-sa@trendaizer.iam.gserviceaccount.com"
          audience: "https://github.com/IstiN/TrendAIzer"
          create_credentials_file: true
          export_environment_variables: true

      - name: Debug GCP Authentication
        run: |
          echo "Credential File: $GOOGLE_APPLICATION_CREDENTIALS"
          cat $GOOGLE_APPLICATION_CREDENTIALS
          gcloud auth list
          gcloud config list
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: trendaizer
          version: 'latest'

      # If you haven't already done so once, from local terminal you need:
      # gcloud projects add-iam-policy-binding trendaizer \
      #   --member="serviceAccount:github-actions-sa@trendaizer.iam.gserviceaccount.com" \
      #   --role="roles/iam.serviceAccountUser"
      # gcloud compute instances add-iam-policy-binding testvm \
      #   --zone=southamerica-east1-b \
      #   --member="serviceAccount:github-actions-sa@trendaizer.iam.gserviceaccount.com" \
      #   --role="roles/compute.osAdminLogin"

      - name: Deploy JAR to GCP VM
        run: |
          gcloud compute scp app/build/libs/trendaizer-${{ steps.extract_tag.outputs.tag_name }}-all.jar testvm:~ --zone=southamerica-east1-b
