name: Run JAR on GCP VM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the JAR to run (e.g., v1.0.0). Leave blank to use the latest tag.'
        required: false
      additional_parameters:
        description: 'Parameters to pass to the JAR (optional)'
        required: false

jobs:
  run-jar:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"
          audience: "https://github.com/IstiN/TrendAIzer"
          create_credentials_file: true
          export_environment_variables: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: 'latest'

      - name: Get Latest Tag or Release
        id: get_latest_version
        run: |
          if [ -z "${{ inputs.version }}" ]; then
            # Fetch all tags
            git fetch --prune --unshallow --tags || true

            # Get the latest tag based on version sorting
            latest_tag=$(git tag --sort=-v:refname | head -n1)

            # Fall back to GitHub API for latest release if no tags are found
            if [ -z "$latest_tag" ]; then
              latest_tag=$(curl -s \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                https://api.github.com/repos/IstiN/TrendAIzer/releases/latest | jq -r .tag_name)
            fi

            echo "Using latest tag: $latest_tag"
            echo "version=$latest_tag" >> $GITHUB_ENV
          else
            echo "Using provided version: ${{ inputs.version }}"
            echo "version=${{ inputs.version }}" >> $GITHUB_ENV
          fi

      - name: Run JAR on GCP VM
        run: |
          echo "Running jar version = ${{ env.version }}"
          gcloud compute ssh ${{ vars.GCP_VM_NAME }} --zone=southamerica-east1-b --command="
            echo 'Starting Java process from /opt/shared...';
            nohup java -cp /opt/shared/trendaizer-${{ env.version }}-all.jar \
              com.github.istin.tradingaizer.IndicatorTestingApp \
              ${{ inputs.additional_parameters }} \
              > /opt/shared/app.log 2>&1 &
            echo 'Java process started';
            sleep 2;  # Give the process time to start
            echo 'Checking process list:';
            ps aux | grep java;
            echo 'Checking logs:';
            tail -n 10 /opt/shared/app.log;
          "
