name: Run JAR on GCP VM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the JAR to run (e.g., v1.0.0). Leave blank to use the latest tag.'
        required: false
      additional_parameters:
        description: 'Parameters to pass to the JAR (optional)'
        required: false

jobs:
  run-jar:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1071463491007/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "github-actions-sa@trendaizer.iam.gserviceaccount.com"
          audience: "https://github.com/IstiN/TrendAIzer"
          create_credentials_file: true
          export_environment_variables: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: trendaizer
          version: 'latest'

      - name: Run JAR on GCP VM
        run: |
          echo "Running jar version = ${{ inputs.version }}"
          gcloud compute ssh testvm --zone=southamerica-east1-b --command="
            echo 'Starting Java process from /opt/shared...';
            nohup java -cp /opt/shared/trendaizer-${{ inputs.version }}-all.jar \
              com.github.istin.tradingaizer.IndicatorTestingApp \
              ${{ inputs.additional_parameters }} \
              > /opt/shared/app.log 2>&1 &
            echo 'Java process started';
            sleep 2;  # Give the process time to start
            echo 'Checking process list:';
            ps aux | grep java;
            echo 'Checking logs:';
            tail -n 10 /opt/shared/app.log;
          "
